
- name: Add repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt {{ansible_distribution_release}}-pgdg main' state=present
 
- name: Add ubuntu gis repository
  apt_repository: repo=ppa:ubuntugis/ubuntugis-unstable state=present


- name: Add key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present

# - name: apt get update
#   apt: repo=ppa:ubuntugis/ubuntugis-unstable update_cache=yes

- name: install packages
  apt: name={{item}} state=present
  with_items:
    - postgresql-{{postgresql.version.major}}.{{postgresql.version.minor}}
    - postgresql-contrib-{{postgresql.version.major}}.{{postgresql.version.minor}}
    - postgresql-server-dev-{{postgresql.version.major}}.{{postgresql.version.minor}}

- name: start postgresql
  service: name=postgresql state=started enabled=yes